In [1]:
import pandas as pd

In [2]:
#create a file that has all NDC-level information for each drug product
#download the 'package' and 'product' files from the FDA website: 
#https://www.fda.gov/drugs/drug-approvals-and-databases/national-drug-code-directory

In [3]:
#load the package file

package = pd.read_csv(r'/Users/barrypeterson/IntegraConnect/ndctext/package.txt',sep ='\t', lineterminator ='\r')

In [4]:
#this file is a tab-delimited .txt file and will need to be converted to .csv to join with other files
package.to_csv (r'/Users/barrypeterson/IntegraConnect/ndccsv/package.csv', index=None)

In [5]:
package.head()

,PRODUCTID,PRODUCTNDC,NDCPACKAGECODE,PACKAGEDESCRIPTION,STARTMARKETINGDATE,ENDMARKETINGDATE,NDC_EXCLUDE_FLAG,SAMPLE_PACKAGE
0,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,0002-0152,0002-0152-01,"1 VIAL, SINGLE-DOSE in 1 CARTON (0002-0152-01)...",20240328.0,NaN,N,N
1,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,0002-0152,0002-0152-04,"4 VIAL, SINGLE-DOSE in 1 CARTON (0002-0152-04)...",20240808.0,NaN,N,N
2,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,0002-0152,0002-0152-61,"4 VIAL, SINGLE-DOSE in 1 CARTON (0002-0152-61)...",20250501.0,NaN,N,Y
3,\n0002-0213_42527ae4-c593-4e13-8b77-c0511198c708,0002-0213,0002-0213-01,"1 VIAL, MULTI-DOSE in 1 CARTON (0002-0213-01) ...",20230620.0,20261215.0,N,N
4,\n0002-0243_f4a0acea-cd2f-4e90-b495-bb07116e0509,0002-0243,0002-0243-01,"1 VIAL, SINGLE-DOSE in 1 CARTON (0002-0243-01)...",20240328.0,NaN,N,N

In [6]:
#modify the saved csv:
#create the 'NDC11' and 'NDCProduct' columns
#split the 'NDCPACKAGECODE' into three columns that are separated by the "-"
#'NDC11' is created by modifying the appropriate section, then concatenating into 11 digits
#'NDCProduct' is created by removing the trailing 2 digits of 'NDC11'
#format the two new fields as 'text' and save the file under a new name (eg package1)

In [7]:
#Jupyter Notebook converts the NDC fields to int64 which removes leading "0's", eliminating its functionality
#prior to uploading the new file: define the data types for specific columns in the package1 file
#by defining 'NDC11' and 'NDCProduct' as 'string' we can retain the leading "0's"

data_types = {
    'PRODUCTID': 'object',  
    'PRODUCTNDC': 'object',   
    'NDCPACKAGECODE': 'object', 
    'NDC11': 'string',
    'NDCProduct': 'string',
    'PACKAGEDESCRIPTION': 'object',
    'STARTMARKETINGDATE': 'Int64',
    'ENDMARKETINGDATE': 'Int64',
    'NDC_EXCLUDE_FLAG': 'object',
    'SAMPLE_PACKAGE': 'object'     
}

In [8]:
#import the package1 modified datafile
#ensure 'productid' is the first column to join on later
package1 = pd.read_csv(r'/Users/barrypeterson/IntegraConnect/ndccsv/package1.csv', dtype=data_types)

In [9]:
package1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211466 entries, 0 to 211465
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   PRODUCTID           211466 non-null  object
 1   NDCProduct          211465 non-null  string
 2   NDC11               211465 non-null  string
 3   PRODUCTNDC          211465 non-null  object
 4   NDCPACKAGECODE      211465 non-null  object
 5   PACKAGEDESCRIPTION  211465 non-null  object
 6   STARTMARKETINGDATE  211465 non-null  Int64
 7   ENDMARKETINGDATE    5433 non-null    Int64
 8   NDC_EXCLUDE_FLAG    211465 non-null  object
 9   SAMPLE_PACKAGE      211465 non-null  object
dtypes: Int64(2), object(6), string(2)
memory usage: 16.5+ MB

In [10]:
package1.head()

,PRODUCTID,NDCProduct,NDC11,PRODUCTNDC,NDCPACKAGECODE,PACKAGEDESCRIPTION,STARTMARKETINGDATE,ENDMARKETINGDATE,NDC_EXCLUDE_FLAG,SAMPLE_PACKAGE
0,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,00020152,00002015201,0002-0152,0002-0152-01,"1 VIAL, SINGLE-DOSE in 1 CARTON (0002-0152-01)...",20240328,<NA>,N,N
1,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,00020152,00002015204,0002-0152,0002-0152-04,"4 VIAL, SINGLE-DOSE in 1 CARTON (0002-0152-04)...",20240808,<NA>,N,N
2,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,00020152,00002015261,0002-0152,0002-0152-61,"4 VIAL, SINGLE-DOSE in 1 CARTON (0002-0152-61)...",20250501,<NA>,N,Y
3,\n0002-0213_42527ae4-c593-4e13-8b77-c0511198c708,00020213,00002021301,0002-0213,0002-0213-01,"1 VIAL, MULTI-DOSE in 1 CARTON (0002-0213-01) ...",20230620,20261215,N,N
4,\n0002-0243_f4a0acea-cd2f-4e90-b495-bb07116e0509,00020243,00002024301,0002-0243,0002-0243-01,"1 VIAL, SINGLE-DOSE in 1 CARTON (0002-0243-01)...",20240328,<NA>,N,N

In [11]:
#can now load the 'product' file to eventually join with the 'package1' file to complete the NDC-level information

In [12]:
#load the product file
#the product file is also a tab-delimited .txt file and will need to be converted to .csv
#jupyter notebook requires encoding in 'windows-1252' to load correctly

product = pd.read_csv (r'/Users/barrypeterson/IntegraConnect/ndctext/product.txt', sep='\t',
                  lineterminator='\r',
                       encoding='windows-1252')

In [13]:
#convert to .csv to join with other files later
product.to_csv (r'/Users/barrypeterson/IntegraConnect/ndccsv/product.csv', index=None)

In [14]:
#the product file contains a number of columns that are unnecessary 
#define the columns needed in the product file and save under a new file name (eg product1)
product1 = product[['PRODUCTID',
                    'PRODUCTTYPENAME',
                    'PROPRIETARYNAME',
                    'PROPRIETARYNAMESUFFIX',
                    'NONPROPRIETARYNAME',
                    'DOSAGEFORMNAME',
                    'ROUTENAME',
                    'LABELERNAME',
                    'SUBSTANCENAME',
                    'ACTIVE_NUMERATOR_STRENGTH',
                    'ACTIVE_INGRED_UNIT',
                    'PHARM_CLASSES',
                    'DEASCHEDULE']]

In [15]:
product1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111656 entries, 0 to 111655
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   PRODUCTID                  111656 non-null  object
 1   PRODUCTTYPENAME            111655 non-null  object
 2   PROPRIETARYNAME            111647 non-null  object
 3   PROPRIETARYNAMESUFFIX      8432 non-null    object
 4   NONPROPRIETARYNAME         111652 non-null  object
 5   DOSAGEFORMNAME             111655 non-null  object
 6   ROUTENAME                  109882 non-null  object
 7   LABELERNAME                111655 non-null  object
 8   SUBSTANCENAME              109354 non-null  object
 9   ACTIVE_NUMERATOR_STRENGTH  109354 non-null  object
 10  ACTIVE_INGRED_UNIT         109354 non-null  object
 11  PHARM_CLASSES              72128 non-null   object
 12  DEASCHEDULE                5203 non-null    object
dtypes: object(13)
memory usage: 11.1+ MB

In [16]:
product1.head()

,PRODUCTID,PRODUCTTYPENAME,PROPRIETARYNAME,PROPRIETARYNAMESUFFIX,NONPROPRIETARYNAME,DOSAGEFORMNAME,ROUTENAME,LABELERNAME,SUBSTANCENAME,ACTIVE_NUMERATOR_STRENGTH,ACTIVE_INGRED_UNIT,PHARM_CLASSES,DEASCHEDULE
0,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,HUMAN PRESCRIPTION DRUG,Zepbound,NaN,tirzepatide,"INJECTION, SOLUTION",SUBCUTANEOUS,Eli Lilly and Company,TIRZEPATIDE,2.5,mg/.5mL,"G-Protein-linked Receptor Interactions [MoA], ...",NaN
1,\n0002-0213_42527ae4-c593-4e13-8b77-c0511198c708,HUMAN OTC DRUG,Humulin,R,Insulin human,"INJECTION, SOLUTION",PARENTERAL,Eli Lilly and Company,INSULIN HUMAN,100,[iU]/mL,"Insulin [CS], Insulin [EPC]",NaN
2,\n0002-0243_f4a0acea-cd2f-4e90-b495-bb07116e0509,HUMAN PRESCRIPTION DRUG,Zepbound,NaN,tirzepatide,"INJECTION, SOLUTION",SUBCUTANEOUS,Eli Lilly and Company,TIRZEPATIDE,5,mg/.5mL,"G-Protein-linked Receptor Interactions [MoA], ...",NaN
3,\n0002-0800_3d52c48f-89cd-4d3d-8db6-1789e76a1c79,HUMAN PRESCRIPTION DRUG,Sterile Diluent,NaN,diluent,"INJECTION, SOLUTION",SUBCUTANEOUS,Eli Lilly and Company,WATER,1,mL/mL,NaN,NaN
4,\n0002-1152_371ba02d-d590-4295-a315-b5efe4596614,HUMAN PRESCRIPTION DRUG,Mounjaro,NaN,tirzepatide,"INJECTION, SOLUTION",SUBCUTANEOUS,Eli Lilly and Company,TIRZEPATIDE,2.5,mg/.5mL,"G-Protein-linked Receptor Interactions [MoA], ...",NaN

In [17]:
#the files are both now loaded and ready to join
#each file contains a line-specific identifier in the 'PRODUCTID' field which we can use to join

In [18]:
#left join on the ProductID associated with each file 
NDC = package1.merge(product1, on='PRODUCTID', how='left')

In [19]:
NDC.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 211466 entries, 0 to 211465
Data columns (total 22 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   PRODUCTID                  211466 non-null  object
 1   NDCProduct                 211465 non-null  string
 2   NDC11                      211465 non-null  string
 3   PRODUCTNDC                 211465 non-null  object
 4   NDCPACKAGECODE             211465 non-null  object
 5   PACKAGEDESCRIPTION         211465 non-null  object
 6   STARTMARKETINGDATE         211465 non-null  Int64
 7   ENDMARKETINGDATE           5433 non-null    Int64
 8   NDC_EXCLUDE_FLAG           211465 non-null  object
 9   SAMPLE_PACKAGE             211465 non-null  object
 10  PRODUCTTYPENAME            211464 non-null  object
 11  PROPRIETARYNAME            211452 non-null  object
 12  PROPRIETARYNAMESUFFIX      12717 non-null   object
 13  NONPROPRIETARYNAME         211460 non-null  object
 14  DOSAGEFORMNAME             211464 non-null  object
 15  ROUTENAME                  209432 non-null  object
 16  LABELERNAME                211464 non-null  object
 17  SUBSTANCENAME              208814 non-null  object
 18  ACTIVE_NUMERATOR_STRENGTH  208814 non-null  object
 19  ACTIVE_INGRED_UNIT         208814 non-null  object
 20  PHARM_CLASSES              140501 non-null  object
 21  DEASCHEDULE                11633 non-null   object
dtypes: Int64(2), object(18), string(2)
memory usage: 37.5+ MB

In [20]:
NDC.head()

,PRODUCTID,NDCProduct,NDC11,PRODUCTNDC,NDCPACKAGECODE,PACKAGEDESCRIPTION,STARTMARKETINGDATE,ENDMARKETINGDATE,NDC_EXCLUDE_FLAG,SAMPLE_PACKAGE,...,PROPRIETARYNAMESUFFIX,NONPROPRIETARYNAME,DOSAGEFORMNAME,ROUTENAME,LABELERNAME,SUBSTANCENAME,ACTIVE_NUMERATOR_STRENGTH,ACTIVE_INGRED_UNIT,PHARM_CLASSES,DEASCHEDULE
0,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,00020152,00002015201,0002-0152,0002-0152-01,"1 VIAL, SINGLE-DOSE in 1 CARTON (0002-0152-01)...",20240328,<NA>,N,N,...,NaN,tirzepatide,"INJECTION, SOLUTION",SUBCUTANEOUS,Eli Lilly and Company,TIRZEPATIDE,2.5,mg/.5mL,"G-Protein-linked Receptor Interactions [MoA], ...",NaN
1,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,00020152,00002015204,0002-0152,0002-0152-04,"4 VIAL, SINGLE-DOSE in 1 CARTON (0002-0152-04)...",20240808,<NA>,N,N,...,NaN,tirzepatide,"INJECTION, SOLUTION",SUBCUTANEOUS,Eli Lilly and Company,TIRZEPATIDE,2.5,mg/.5mL,"G-Protein-linked Receptor Interactions [MoA], ...",NaN
2,\n0002-0152_f4a0acea-cd2f-4e90-b495-bb07116e0509,00020152,00002015261,0002-0152,0002-0152-61,"4 VIAL, SINGLE-DOSE in 1 CARTON (0002-0152-61)...",20250501,<NA>,N,Y,...,NaN,tirzepatide,"INJECTION, SOLUTION",SUBCUTANEOUS,Eli Lilly and Company,TIRZEPATIDE,2.5,mg/.5mL,"G-Protein-linked Receptor Interactions [MoA], ...",NaN
3,\n0002-0213_42527ae4-c593-4e13-8b77-c0511198c708,00020213,00002021301,0002-0213,0002-0213-01,"1 VIAL, MULTI-DOSE in 1 CARTON (0002-0213-01) ...",20230620,20261215,N,N,...,R,Insulin human,"INJECTION, SOLUTION",PARENTERAL,Eli Lilly and Company,INSULIN HUMAN,100,[iU]/mL,"Insulin [CS], Insulin [EPC]",NaN
4,\n0002-0243_f4a0acea-cd2f-4e90-b495-bb07116e0509,00020243,00002024301,0002-0243,0002-0243-01,"1 VIAL, SINGLE-DOSE in 1 CARTON (0002-0243-01)...",20240328,<NA>,N,N,...,NaN,tirzepatide,"INJECTION, SOLUTION",SUBCUTANEOUS,Eli Lilly and Company,TIRZEPATIDE,5,mg/.5mL,"G-Protein-linked Receptor Interactions [MoA], ...",NaN

In [21]:
#no longer need NDC-join-related information, so will drop the 'ProductID' field

NDC = NDC.drop(['PRODUCTID'], axis=1)

In [22]:
#the drug-related NDC file is now created, 
#need to now begin to add-in additional oncology-related information

In [23]:
#Download the most recent oncology-NDC information from SEER:
#https://seer.cancer.gov/oncologytoolbox/canmed/ndconc/?ordering=None&&page=490

In [45]:
#modify and add the NDC field into an NDC11 field in the initial column area

#define the file columns to upload the NDC11 field:
data_types3 = {
    'NDC11':  'object', 
    'NDC-11 (Package)': 'object',
    'NDC-9 (Product)': 'object',
    'Generic Name': 'object',
    'Brand Name': 'object',
    'Strength': 'object',
    'SEER*Rx Category': 'object',
    'Major Class': 'object',
    'Minor Class': 'object',
    'Administration Route': 'object',
    'Package Effective Date': 'object',
    'Package Discontinuation Date': 'object',
    'Status': 'object'    
}

In [54]:
#upload the SEER NDC file

SEER_NDC = pd.read_csv(r'/Users/barrypeterson/IntegraConnect/ndccsv/SEER NDC.csv', dtype = data_types3)

In [55]:
SEER_NDC.head()

,NDC11,NDC-11 (Package),NDC-9 (Product),Generic Name,Brand Name,Strength,SEER*Rx Category,Major Class,Minor Class,Administration Route,Package Effective Date,Package Discontinuation Date,Status
0,00002171728,00002-1717-28,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,10/16/25,NaN,In Use
1,00002171756,00002-1717-56,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,10/15/25,NaN,In Use
2,00002171761,00002-1717-61,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,11/13/25,NaN,In Use
3,00002298026,00002-2980-26,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,5/8/20,NaN,In Use
4,00002298060,00002-2980-60,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,5/8/20,NaN,In Use

In [56]:
SEER_NDC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12250 entries, 0 to 12249
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   NDC11                         12250 non-null  object
 1   NDC-11 (Package)              12250 non-null  object
 2   NDC-9 (Product)               12250 non-null  object
 3   Generic Name                  12250 non-null  object
 4   Brand Name                    12250 non-null  object
 5   Strength                      11406 non-null  object
 6   SEER*Rx Category              12250 non-null  object
 7   Major Class                   12250 non-null  object
 8   Minor Class                   10703 non-null  object
 9   Administration Route          11971 non-null  object
 10  Package Effective Date        12241 non-null  object
 11  Package Discontinuation Date  3832 non-null   object
 12  Status                        12250 non-null  object
dtypes: object(13)
memory usage: 1.2+ MB

In [57]:
#join the NDC file to SEER_NDC to obtain baseline oncology information for each NDC
SEER_NDC_File = pd.merge(SEER_NDC, NDC, on='NDC11', how='left')

In [58]:
SEER_NDC_File.head()

,NDC11,NDC-11 (Package),NDC-9 (Product),Generic Name,Brand Name,Strength,SEER*Rx Category,Major Class,Minor Class,Administration Route,...,PROPRIETARYNAMESUFFIX,NONPROPRIETARYNAME,DOSAGEFORMNAME,ROUTENAME,LABELERNAME,SUBSTANCENAME,ACTIVE_NUMERATOR_STRENGTH,ACTIVE_INGRED_UNIT,PHARM_CLASSES,DEASCHEDULE
0,00002171728,00002-1717-28,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,imlunestrant,"TABLET, FILM COATED",ORAL,Eli Lilly and Company,IMLUNESTRANT,200,mg/1,Breast Cancer Resistance Protein Inhibitors [M...,NaN
1,00002171756,00002-1717-56,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,imlunestrant,"TABLET, FILM COATED",ORAL,Eli Lilly and Company,IMLUNESTRANT,200,mg/1,Breast Cancer Resistance Protein Inhibitors [M...,NaN
2,00002171761,00002-1717-61,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,imlunestrant,"TABLET, FILM COATED",ORAL,Eli Lilly and Company,IMLUNESTRANT,200,mg/1,Breast Cancer Resistance Protein Inhibitors [M...,NaN
3,00002298026,00002-2980-26,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,...,NaN,selpercatinib,CAPSULE,ORAL,Eli Lilly and Company,SELPERCATINIB,80,mg/1,Breast Cancer Resistance Protein Inhibitors [M...,NaN
4,00002298060,00002-2980-60,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,...,NaN,selpercatinib,CAPSULE,ORAL,Eli Lilly and Company,SELPERCATINIB,80,mg/1,Breast Cancer Resistance Protein Inhibitors [M...,NaN

In [59]:
SEER_NDC_File.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12250 entries, 0 to 12249
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   NDC11                         12250 non-null  object
 1   NDC-11 (Package)              12250 non-null  object
 2   NDC-9 (Product)               12250 non-null  object
 3   Generic Name                  12250 non-null  object
 4   Brand Name                    12250 non-null  object
 5   Strength                      11406 non-null  object
 6   SEER*Rx Category              12250 non-null  object
 7   Major Class                   12250 non-null  object
 8   Minor Class                   10703 non-null  object
 9   Administration Route          11971 non-null  object
 10  Package Effective Date        12241 non-null  object
 11  Package Discontinuation Date  3832 non-null   object
 12  Status                        12250 non-null  object
 13  NDCProduct                    5637 non-null   string
 14  PRODUCTNDC                    5637 non-null   object
 15  NDCPACKAGECODE                5637 non-null   object
 16  PACKAGEDESCRIPTION            5637 non-null   object
 17  STARTMARKETINGDATE            5637 non-null   Int64
 18  ENDMARKETINGDATE              144 non-null    Int64
 19  NDC_EXCLUDE_FLAG              5637 non-null   object
 20  SAMPLE_PACKAGE                5637 non-null   object
 21  PRODUCTTYPENAME               5637 non-null   object
 22  PROPRIETARYNAME               5637 non-null   object
 23  PROPRIETARYNAMESUFFIX         38 non-null     object
 24  NONPROPRIETARYNAME            5637 non-null   object
 25  DOSAGEFORMNAME                5637 non-null   object
 26  ROUTENAME                     5555 non-null   object
 27  LABELERNAME                   5637 non-null   object
 28  SUBSTANCENAME                 5523 non-null   object
 29  ACTIVE_NUMERATOR_STRENGTH     5523 non-null   object
 30  ACTIVE_INGRED_UNIT            5523 non-null   object
 31  PHARM_CLASSES                 5302 non-null   object
 32  DEASCHEDULE                   25 non-null     object
dtypes: Int64(2), object(30), string(1)
memory usage: 3.2+ MB

In [60]:
#SEER_NDC_File contains NDC-level information for all oncology-related medications with baseline oncology info
#Now need to add additional oncology information

In [61]:
#Can now add billable units to this file based on J Code number

In [62]:
#download the most recent billable file from:
#https://www.dmepdac.com/palmetto/PDACv2.nsf/T/NDC-+-HCPCS%20Crosswalk

In [63]:
#modify the file to create an 'NDC11' column as before
#eliminate the terminal 6 columns and the 'HCPCS mod' column as they are unnecessary

In [64]:
#define data types as before to retain functinality of the NDC columns
data_types2 = {
    'NDC11': 'object',  
    'HCPCS': 'object', 
    'Relationship Start Date': 'object',
    'Relationship End Date': 'object', 
    'HCPCS Description': 'object', 
    'NDC Label': 'object',
    'Number of Items in NDC Package': 'float64',
    'NDC Package Measure': 'object',
    'NDC Package Type': 'object', 
    'Route of Administration': 'object', 
    'Billing Units': 'object',
    'HCPCS Amount #1': 'float64',
    'HCPCS Measure #1': 'object', 
    'CF': 'float64',
    'Start Date #1': 'object', 
    'End Date #1': 'object'      
}

In [65]:
#Upload the modified billable units file - dropped columns and NDC modified to 11 digits no "-"

HCPCS_Billable = pd.read_csv(r'/Users/barrypeterson/IntegraConnect/CrossWalk/HCPCS_Billable.csv', dtype=data_types2)

In [66]:
HCPCS_Billable.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11240 entries, 0 to 11239
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NDC11                           11240 non-null  object
 1   HCPCS                           11240 non-null  object
 2   Relationship Start Date         11240 non-null  object
 3   Relationship End Date           11240 non-null  object
 4   HCPCS Description               11240 non-null  object
 5   NDC Label                       11240 non-null  object
 6   Number of Items in NDC Package  11240 non-null  float64
 7   NDC Package Measure             11240 non-null  object
 8   NDC Package Type                8839 non-null   object
 9   Route of Administration         10201 non-null  object
 10  Billing Units                   11240 non-null  object
 11  HCPCS Amount #1                 11240 non-null  float64
 12  HCPCS Measure #1                11239 non-null  object
 13  CF                              11240 non-null  float64
 14  Start Date #1                   11240 non-null  object
 15  End Date #1                     11240 non-null  object
dtypes: float64(3), object(13)
memory usage: 1.4+ MB

In [67]:
HCPCS_Billable.head()

,NDC11,HCPCS,Relationship Start Date,Relationship End Date,HCPCS Description,NDC Label,Number of Items in NDC Package,NDC Package Measure,NDC Package Type,Route of Administration,Billing Units,HCPCS Amount #1,HCPCS Measure #1,CF,Start Date #1,End Date #1
0,00002733511,J2941,3/1/06,12/31/20,"INJECTION, SOMATROPIN, 1 MG",HUMATROPE (WITH STERILE DILUENT) 5 MG,1.0,EA,VL,SC,EA,1.0,MG,5.0,3/1/06,12/31/20
1,00002751001,J1817,1/1/03,99/99/9999,"INSULIN FOR ADMINISTRATION THROUGH DME (I.E., ...",HUMALOG (VIAL) 100 U/ML,10.0,ML,VL,SC,ML,50.0,U,2.0,1/1/03,99/99/9999
2,00002751099,J1817,7/24/96,99/99/9999,"INSULIN FOR ADMINISTRATION THROUGH DME (I.E., ...",HUMALOG (VIAL) 100 U/1 ML,10.0,ML,VL,IJ,ML,50.0,U,2.0,7/24/96,99/99/9999
3,00002751101,J1815,1/1/03,99/99/9999,"INJECTION, INSULIN, PER 5 UNITS",HUMALOG MIX 75/25 (VIAL) 75 U/ML-25 U/ML,10.0,ML,VL,SC,ML,5.0,U,20.0,1/1/03,99/99/9999
4,00002751199,J1815,12/7/07,9/18/25,"INJECTION, INSULIN, PER 5 UNITS",HUMALOG MIX 75/25 (VIAL) 75 U/1 ML-25 U/1 ML,10.0,ML,VL,SC,ML,5.0,U,20.0,12/7/07,9/18/25

In [68]:
#merge HCPCS_Billable file into SEER_NDC_File to acquire billing information for all J-Code related meds

In [93]:
SEER_Billable = pd.merge(SEER_NDC_File, HCPCS_Billable, on='NDC11', how='left')

In [94]:
SEER_Billable.head()

,NDC11,NDC-11 (Package),NDC-9 (Product),Generic Name,Brand Name,Strength,SEER*Rx Category,Major Class,Minor Class,Administration Route,...,Number of Items in NDC Package,NDC Package Measure,NDC Package Type,Route of Administration,Billing Units,HCPCS Amount #1,HCPCS Measure #1,CF,Start Date #1,End Date #1
0,00002171728,00002-1717-28,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00002171756,00002-1717-56,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00002171761,00002-1717-61,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00002298026,00002-2980-26,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00002298060,00002-2980-60,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
SEER_Billable.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12399 entries, 0 to 12398
Data columns (total 48 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NDC11                           12399 non-null  object
 1   NDC-11 (Package)                12399 non-null  object
 2   NDC-9 (Product)                 12399 non-null  object
 3   Generic Name                    12399 non-null  object
 4   Brand Name                      12399 non-null  object
 5   Strength                        11552 non-null  object
 6   SEER*Rx Category                12399 non-null  object
 7   Major Class                     12399 non-null  object
 8   Minor Class                     10850 non-null  object
 9   Administration Route            12119 non-null  object
 10  Package Effective Date          12390 non-null  object
 11  Package Discontinuation Date    3852 non-null   object
 12  Status                          12399 non-null  object
 13  NDCProduct                      5757 non-null   string
 14  PRODUCTNDC                      5757 non-null   object
 15  NDCPACKAGECODE                  5757 non-null   object
 16  PACKAGEDESCRIPTION              5757 non-null   object
 17  STARTMARKETINGDATE              5757 non-null   Int64
 18  ENDMARKETINGDATE                147 non-null    Int64
 19  NDC_EXCLUDE_FLAG                5757 non-null   object
 20  SAMPLE_PACKAGE                  5757 non-null   object
 21  PRODUCTTYPENAME                 5757 non-null   object
 22  PROPRIETARYNAME                 5757 non-null   object
 23  PROPRIETARYNAMESUFFIX           38 non-null     object
 24  NONPROPRIETARYNAME              5757 non-null   object
 25  DOSAGEFORMNAME                  5757 non-null   object
 26  ROUTENAME                       5672 non-null   object
 27  LABELERNAME                     5757 non-null   object
 28  SUBSTANCENAME                   5640 non-null   object
 29  ACTIVE_NUMERATOR_STRENGTH       5640 non-null   object
 30  ACTIVE_INGRED_UNIT              5640 non-null   object
 31  PHARM_CLASSES                   5405 non-null   object
 32  DEASCHEDULE                     25 non-null     object
 33  HCPCS                           2496 non-null   object
 34  Relationship Start Date         2496 non-null   object
 35  Relationship End Date           2496 non-null   object
 36  HCPCS Description               2496 non-null   object
 37  NDC Label                       2496 non-null   object
 38  Number of Items in NDC Package  2496 non-null   float64
 39  NDC Package Measure             2496 non-null   object
 40  NDC Package Type                2027 non-null   object
 41  Route of Administration         2496 non-null   object
 42  Billing Units                   2496 non-null   object
 43  HCPCS Amount #1                 2496 non-null   float64
 44  HCPCS Measure #1                2495 non-null   object
 45  CF                              2496 non-null   float64
 46  Start Date #1                   2496 non-null   object
 47  End Date #1                     2496 non-null   object
dtypes: Int64(2), float64(3), object(42), string(1)
memory usage: 4.7+ MB

In [189]:
#Last step is to add-in IntegraConnect specific information we want in the Master Drug File
#Upload the oncology list of drugs
Drug_List_Generic = pd.read_csv(r'/Users/barrypeterson/IntegraConnect/Master Drug Reference/Drug_List_Generic.csv')

In [190]:
Drug_List_Generic.head()

,Trade Name,Generic Name,HCPCS,HCPCS Description,Is Chemo (Y/N),Is Targeted (Y/N),Is Immunotherapy (Y/N),Is Supportive (Y/N),Is Hormonal (Y/N),Is Radiotherapy (Y/N)
0,"A-Methapred, SOLU-medrol",Methylprednisolone Sodium Succinate,J2920,"Injection, methylprednisolone sodium succinate...",No,No,No,Yes,No,No
1,"A-Methapred, SOLU-medrol",Methylprednisolone Sodium Succinate,J2930,"Injection, methylprednisolone sodium succinate...",No,No,No,Yes,No,No
2,Abecma,Idecabtagene vicleucel,C9081,"Idecabtagene vicleucel, up to 460 million auto...",No,Yes,Yes,No,No,No
3,Abecma,Idecabtagene vicleucel,Q2055,"Idecabtagene vicleucel, up to 510 million auto...",No,Yes,Yes,No,No,No
4,Abraxane,Paclitaxel protein-bound particles,J9264,"Injection, paclitaxel protein-bound particles,...",Yes,No,No,No,No,No

In [191]:
Drug_List_Generic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785 entries, 0 to 784
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Trade Name              785 non-null    object
 1   Generic Name            785 non-null    object
 2   HCPCS                   599 non-null    object
 3   HCPCS Description       785 non-null    object
 4   Is Chemo (Y/N)          785 non-null    object
 5   Is Targeted (Y/N)       784 non-null    object
 6   Is Immunotherapy (Y/N)  784 non-null    object
 7   Is Supportive (Y/N)     784 non-null    object
 8   Is Hormonal (Y/N)       784 non-null    object
 9   Is Radiotherapy (Y/N)   784 non-null    object
dtypes: object(10)
memory usage: 61.5+ KB

In [192]:
#join on HCPCS code to create the final Master Drug File


#foo.merge(bar[pd.notnull(bar.id)], how='left', on='id')

#Master_Drug_File2 = SEER_Billable.merge(Drug_List[pd.notnull(SEER_Billable.HCPCS)], how='left', on='HCPCS')

Master_Drug_File2 = pd.merge(SEER_Billable, Drug_List_Generic, on='Generic Name', how='left')

In [193]:
Master_Drug_File2.head()

,NDC11,NDC-11 (Package),NDC-9 (Product),Generic Name,Brand Name,Strength,SEER*Rx Category,Major Class,Minor Class,Administration Route,...,End Date #1,Trade Name,HCPCS_y,HCPCS Description_y,Is Chemo (Y/N),Is Targeted (Y/N),Is Immunotherapy (Y/N),Is Supportive (Y/N),Is Hormonal (Y/N),Is Radiotherapy (Y/N)
0,00002171728,00002-1717-28,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00002171756,00002-1717-56,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00002171761,00002-1717-61,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00002298026,00002-2980-26,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,...,NaN,Retevmo,NaN,Retevmo,No,Yes,No,No,No,No
4,00002298060,00002-2980-60,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,...,NaN,Retevmo,NaN,Retevmo,No,Yes,No,No,No,No

In [194]:
Master_Drug_File2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26688 entries, 0 to 26687
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NDC11                           26688 non-null  object
 1   NDC-11 (Package)                26688 non-null  object
 2   NDC-9 (Product)                 26688 non-null  object
 3   Generic Name                    26688 non-null  object
 4   Brand Name                      26688 non-null  object
 5   Strength                        24876 non-null  object
 6   SEER*Rx Category                26688 non-null  object
 7   Major Class                     26688 non-null  object
 8   Minor Class                     24389 non-null  object
 9   Administration Route            26145 non-null  object
 10  Package Effective Date          26675 non-null  object
 11  Package Discontinuation Date    8310 non-null   object
 12  Status                          26688 non-null  object
 13  NDCProduct                      11805 non-null  string
 14  PRODUCTNDC                      11805 non-null  object
 15  NDCPACKAGECODE                  11805 non-null  object
 16  PACKAGEDESCRIPTION              11805 non-null  object
 17  STARTMARKETINGDATE              11805 non-null  Int64
 18  ENDMARKETINGDATE                314 non-null    Int64
 19  NDC_EXCLUDE_FLAG                11805 non-null  object
 20  SAMPLE_PACKAGE                  11805 non-null  object
 21  PRODUCTTYPENAME                 11805 non-null  object
 22  PROPRIETARYNAME                 11805 non-null  object
 23  PROPRIETARYNAMESUFFIX           90 non-null     object
 24  NONPROPRIETARYNAME              11805 non-null  object
 25  DOSAGEFORMNAME                  11805 non-null  object
 26  ROUTENAME                       11614 non-null  object
 27  LABELERNAME                     11805 non-null  object
 28  SUBSTANCENAME                   11551 non-null  object
 29  ACTIVE_NUMERATOR_STRENGTH       11551 non-null  object
 30  ACTIVE_INGRED_UNIT              11551 non-null  object
 31  PHARM_CLASSES                   9848 non-null   object
 32  DEASCHEDULE                     35 non-null     object
 33  HCPCS_x                         7075 non-null   object
 34  Relationship Start Date         7075 non-null   object
 35  Relationship End Date           7075 non-null   object
 36  HCPCS Description_x             7075 non-null   object
 37  NDC Label                       7075 non-null   object
 38  Number of Items in NDC Package  7075 non-null   float64
 39  NDC Package Measure             7075 non-null   object
 40  NDC Package Type                5279 non-null   object
 41  Route of Administration         7075 non-null   object
 42  Billing Units                   7075 non-null   object
 43  HCPCS Amount #1                 7075 non-null   float64
 44  HCPCS Measure #1                7074 non-null   object
 45  CF                              7075 non-null   float64
 46  Start Date #1                   7075 non-null   object
 47  End Date #1                     7075 non-null   object
 48  Trade Name                      22142 non-null  object
 49  HCPCS_y                         20863 non-null  object
 50  HCPCS Description_y             22142 non-null  object
 51  Is Chemo (Y/N)                  22142 non-null  object
 52  Is Targeted (Y/N)               22132 non-null  object
 53  Is Immunotherapy (Y/N)          22132 non-null  object
 54  Is Supportive (Y/N)             22132 non-null  object
 55  Is Hormonal (Y/N)               22132 non-null  object
 56  Is Radiotherapy (Y/N)           22132 non-null  object
dtypes: Int64(2), float64(3), object(51), string(1)
memory usage: 11.9+ MB

In [195]:
#remove duplicate columns after join

Master_Drug_File2 = Master_Drug_File2.drop(columns=['PRODUCTNDC', 'NDCPACKAGECODE', 'STARTMARKETINGDATE', 'ENDMARKETINGDATE', 'NDC_EXCLUDE_FLAG', 'SAMPLE_PACKAGE', 'HCPCS_x', 'HCPCS Description_x'], axis = 1)

In [196]:
#rename columns that were duplicated during join


Master_Drug_File2.rename(columns={'HCPCS_y': 'HCPCS', 'HCPCS Description_y': 'HCPCS Description'}, inplace=True)

In [197]:
Master_Drug_File2.head()

,NDC11,NDC-11 (Package),NDC-9 (Product),Generic Name,Brand Name,Strength,SEER*Rx Category,Major Class,Minor Class,Administration Route,...,End Date #1,Trade Name,HCPCS,HCPCS Description,Is Chemo (Y/N),Is Targeted (Y/N),Is Immunotherapy (Y/N),Is Supportive (Y/N),Is Hormonal (Y/N),Is Radiotherapy (Y/N)
0,00002171728,00002-1717-28,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00002171756,00002-1717-56,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00002171761,00002-1717-61,00002-1717,Imlunestrant,Inluriyo,200.0 mg/1,Hormonal Therapy,Estrogen Receptor Antagonist,ER⍺,Oral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00002298026,00002-2980-26,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,...,NaN,Retevmo,NaN,Retevmo,No,Yes,No,No,No,No
4,00002298060,00002-2980-60,00002-2980,Selpercatinib,RETEVMO,80.0 mg/1,Chemotherapy,Tyrosine Kinase Inhibitor,VEGFR,Oral,...,NaN,Retevmo,NaN,Retevmo,No,Yes,No,No,No,No

In [198]:
Master_Drug_File2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26688 entries, 0 to 26687
Data columns (total 49 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NDC11                           26688 non-null  object
 1   NDC-11 (Package)                26688 non-null  object
 2   NDC-9 (Product)                 26688 non-null  object
 3   Generic Name                    26688 non-null  object
 4   Brand Name                      26688 non-null  object
 5   Strength                        24876 non-null  object
 6   SEER*Rx Category                26688 non-null  object
 7   Major Class                     26688 non-null  object
 8   Minor Class                     24389 non-null  object
 9   Administration Route            26145 non-null  object
 10  Package Effective Date          26675 non-null  object
 11  Package Discontinuation Date    8310 non-null   object
 12  Status                          26688 non-null  object
 13  NDCProduct                      11805 non-null  string
 14  PACKAGEDESCRIPTION              11805 non-null  object
 15  PRODUCTTYPENAME                 11805 non-null  object
 16  PROPRIETARYNAME                 11805 non-null  object
 17  PROPRIETARYNAMESUFFIX           90 non-null     object
 18  NONPROPRIETARYNAME              11805 non-null  object
 19  DOSAGEFORMNAME                  11805 non-null  object
 20  ROUTENAME                       11614 non-null  object
 21  LABELERNAME                     11805 non-null  object
 22  SUBSTANCENAME                   11551 non-null  object
 23  ACTIVE_NUMERATOR_STRENGTH       11551 non-null  object
 24  ACTIVE_INGRED_UNIT              11551 non-null  object
 25  PHARM_CLASSES                   9848 non-null   object
 26  DEASCHEDULE                     35 non-null     object
 27  Relationship Start Date         7075 non-null   object
 28  Relationship End Date           7075 non-null   object
 29  NDC Label                       7075 non-null   object
 30  Number of Items in NDC Package  7075 non-null   float64
 31  NDC Package Measure             7075 non-null   object
 32  NDC Package Type                5279 non-null   object
 33  Route of Administration         7075 non-null   object
 34  Billing Units                   7075 non-null   object
 35  HCPCS Amount #1                 7075 non-null   float64
 36  HCPCS Measure #1                7074 non-null   object
 37  CF                              7075 non-null   float64
 38  Start Date #1                   7075 non-null   object
 39  End Date #1                     7075 non-null   object
 40  Trade Name                      22142 non-null  object
 41  HCPCS                           20863 non-null  object
 42  HCPCS Description               22142 non-null  object
 43  Is Chemo (Y/N)                  22142 non-null  object
 44  Is Targeted (Y/N)               22132 non-null  object
 45  Is Immunotherapy (Y/N)          22132 non-null  object
 46  Is Supportive (Y/N)             22132 non-null  object
 47  Is Hormonal (Y/N)               22132 non-null  object
 48  Is Radiotherapy (Y/N)           22132 non-null  object
dtypes: float64(3), object(45), string(1)
memory usage: 10.2+ MB

In [200]:
#Rearrange columns to download


Master_Drug_File2 = Master_Drug_File2[['Brand Name',
                                       'Trade Name',
                                       'Generic Name',
                                       'Strength',
                                       'ACTIVE_NUMERATOR_STRENGTH',
                                       'ACTIVE_INGRED_UNIT', 
                                       'DOSAGEFORMNAME', 
                                       'ROUTENAME',
                                       'Route of Administration',
                                       'Administration Route',
                                       'PHARM_CLASSES',
                                       'SEER*Rx Category',
                                       'Major Class',
                                       'Minor Class',
                                       'PROPRIETARYNAME',
                                       'PROPRIETARYNAMESUFFIX',
                                       'NONPROPRIETARYNAME',
                                       'SUBSTANCENAME',
                                       'DEASCHEDULE',
                                       'Status',
                                       'NDC11',
                                       'NDC-11 (Package)',
                                       'NDC-9 (Product)',
                                       'NDCProduct',
                                       'PACKAGEDESCRIPTION',
                                       'PRODUCTTYPENAME',
                                       'LABELERNAME',
                                       'Package Effective Date',
                                       'Package Discontinuation Date',
                                       'Relationship Start Date',
                                       'Relationship End Date',
                                       'NDC Label',
                                       'Number of Items in NDC Package',
                                       'NDC Package Measure',
                                       'NDC Package Type',
                                       'Billing Units',
                                       'HCPCS Amount #1',
                                       'HCPCS Measure #1',
                                       'Start Date #1',
                                       'End Date #1',
                                       'HCPCS',
                                       'HCPCS Description',
                                       'Is Chemo (Y/N)',
                                       'Is Targeted (Y/N)',
                                       'Is Immunotherapy (Y/N)',
                                       'Is Supportive (Y/N)',
                                       'Is Hormonal (Y/N)',
                                       'Is Radiotherapy (Y/N)'
                                      ]]

In [201]:
#Download the Master Drug File to inspect/use 

Master_Drug_File2.to_csv (r'/Users/barrypeterson/IntegraConnect/Master Drug Reference/Master_Drug_File2.csv', index=None)

In [152]:
#Download the SEER_Billable
SEER_Billable.to_csv (r'/Users/barrypeterson/IntegraConnect/CrossWalk/SEER_Billable.csv', index=None)